"""add per-category scores

Revision ID: 84f4fef931dd
Revises: 9cb012b9a07f
Create Date: 2026-07-30 03:46:39.826553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84f4fef931dd'
down_revision: Union[str, Sequence[str], None] = '9cb012b9a07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is NOT autogenerated and is required here. Alembic emits a
    # bare NOT NULL column, which succeeds against an empty database and fails
    # against any table that already has rows:
    #
    #   NotNullViolationError: column "category_scores" of relation "scans"
    #   contains null values
    #
    # The default backfills existing scans with an empty map, which is the
    # honest value for them — they were scored before per-category points were
    # recorded, so nothing is known about how each category did.
    op.add_column(
        'scans',
        sa.Column(
            'category_scores',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'category_scores')
    # ### end Alembic commands ###
