"""add commit context to scans

Revision ID: 9ec37ace7d89
Revises: ff9488965254
Create Date: 2026-07-31 14:39:04.910698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec37ace7d89'
down_revision: Union[str, Sequence[str], None] = 'ff9488965254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('commit_sha', sa.String(length=40), nullable=True))
    op.add_column('scans', sa.Column('commit_message', sa.String(length=500), nullable=True))
    op.add_column('scans', sa.Column('commit_author', sa.String(length=255), nullable=True))
    op.add_column('scans', sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'committed_at')
    op.drop_column('scans', 'commit_author')
    op.drop_column('scans', 'commit_message')
    op.drop_column('scans', 'commit_sha')
    # ### end Alembic commands ###
