"""add scan name and completed at

Revision ID: c2aea0cb546b
Revises: bea16a836eab
Create Date: 2026-08-01 04:49:30.691632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2aea0cb546b'
down_revision: Union[str, Sequence[str], None] = 'bea16a836eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('scans', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'completed_at')
    op.drop_column('scans', 'name')
    # ### end Alembic commands ###
