"""add failure diagnostics to scans

Revision ID: fba77e207623
Revises: 9ec37ace7d89
Create Date: 2026-07-31 15:32:37.269279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba77e207623'
down_revision: Union[str, Sequence[str], None] = '9ec37ace7d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('error_category', sa.String(length=40), nullable=True))
    op.add_column('scans', sa.Column('error_detail', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'error_detail')
    op.drop_column('scans', 'error_category')
    # ### end Alembic commands ###
